FROM gcr.io/marketplace.gcr.io/google/rbe-ubuntu18-04:latest@sha256:48b67b41118dbcdfc265e7335f454fbefa62681ab8d47200971fc7a52fb32054


RUN apt-get update && \
    apt-get install -y cmake clang musl-dev openssl
